# ======================================================================

# CluStR configuration file.
#
# Lines starting with '#' are ignored; all other lines must contain a
# Name : Value pair to be read into the parameters dictionary.

# Spencer Everett, Jose E. Jobel, Paige Kelly, UCSC, 2017 - 2021

# ======================================================================

# ----------------------------------------------------------------------
# General
# --------

# Plots are currently cosmology dependent as luminosities are scaled by E(z)
Om: 0.3
H_0: 0.7

#-----------------------------------------------------------------------
# Scale
#--------
scale_x_by_ez : scale_x_by_ez
scale_y_by_ez : scale_y_by_ez
#------------------------------------------------------------------------

# NB: Not all default options are implemented yet!

# Default observed data catalog:
default_catalog: None

# Default output file prexfix (includes x and y labels automatically)
default_prefix: Jose

# Default covariate variable (independent variable)
default_x: None

# Default response variable (dependent variable)
default_y: None

# Column name conventions:
Column_Names:
    lambda: lambda
    l500kpc: 500_kiloparsecs_band_lumin
    lr2500: r2500_band_lumin
    lr500: r500_band_lumin
    lr500cc: r500_core_cropped_band_lumin
    t500kpc: 500_kiloparsecs_temperature
    tr2500: r2500_temperature
    tr500: r500_temperature
    tr500cc: r500_core_cropped_temperature

# ----------------------------------------------------------------------
# Flags
# --------

# Set desired flag cuts. Cuts can be `bool`, `range`, or `cutoff` in nature.
# For each type, indicate which values you want used in the analysis (e.g.
# `True`/`False` for bool, `above`/`below` for cutoff, `inside`/`outside` for
# range).

# NOTE: Any given column can only be flagged as one flag type - not more!

# NOTE: These flag cut values are not used by default. To apply these flags
#           change the KEY to TRUE.

# To add a new boolean flag use the following structure,

# Bool_Flags:
#   New_flag1_bool_type: True/False
#   New_flag2_bool_type: True/False
#   New_flag3_bool_type: True/False

# To add a new cutoff flag,
#
# Cutoff_Flag:
#   New_flag4:
#       True/Flase:
#           New_flag4_cutoff: value
#           New_flag4_cut_type: above/below
#
# To add a new range flag,

# Range_Flag:
#   New_flag5:
#       True/False:
#           New_flag5_minmax:
#               New_flag5_range_min: value,
#               New_flag5_range_max: value,
#               New_flag5_range_type: outside/inside

# For bools, add the suffix `_bool_type` to the column name.

# cutoff example:
# offset_r500_cut : 0.5
# offset_r500_cut_type : below

# Bools:
Bool_Flag:
    Analyzed_bool_type: False
    bad_mode_bool_type: True
    Detected_bool_type: False
    edge_r500_bool_type: False
    edge_r2500_bool_type: True
    edge_bkgd_bool_type: True
    merger_bool_type: False
    masked_bool_type: True
    overlap_r500_bool_type: True
    overlap_r2500_bool_type: True
    overlap_bkgd_bool_type: True
    Serendipitous_bool_type: False

# Cutoff:
Cutoff_Flag:
    500_kiloparsecs_SNR:
        True:
            SNR_cutoff: 9.0
            #SNR_cut_type: below
  #  Other:
  #      True/False:
  #          _cutoff: value
  #          _cut_type: above/below

# Ranges:
Range_Flag:
    Redshift:
        True:
            Redshift_minmax:
                Redshift_range_min: 0.0
                Redshift_range_max: 1.0
                Redshift_range_type: inside
    Other:
        True/False:
            _minmax:
                _range_min: value
                _range_max: value
                _range_type: outside/inside

# ----------------------------------------------------------------------
# Plots
# --------

# Set which plots you want saved in the output .pdf file. Combines all plots
# into a single file unless `save_all_plots` is set to True.
scatter: True
corner: True
chains: True
residuals: True
save_all_plots: True

# Show the method name used in the scatter plot?
show_method_name: False

# Set burn in period for chain plots (currently only for Mantz)
burn: 0

# ----------------------------------------------------------------------
# Data
# --------

# The used data and regression parameters can be saved independent of plots
save_data: False
output_filename: Test1_lr2500_lambda

# ======================================================================
