name: clustr
channels:
- conda-forge
- defaults
dependencies:
- astropy
- matplotlib
- pip
- python=3
- scipy
- pyyaml
- pyfiglet
- pip:
  - corner
  - pypdf2
  - "git+https://github.com/jmeyers314/linmix.git"
