name: clustr2
channels:
- defaults
dependencies:
- astropy=1.3.2
- matplotlib=2.0.0
- pip=9.0.1
- python=2.7.13
- r-essentials=1.5.2
- rpy2=2.8.5
- scipy=0.19.0
- pip:
  - corner==2.0.0
  - pypdf2==1.26.0
  - "git+https://github.com/jmeyers314/linmix.git"
