name: clustrpy3
channels:
- conda-forge
- defaults
dependencies:
- astropy=4.0.1
- matplotlib=3.4.2
- pip=20.2.2
- python=3.9.2
- r-essentials=3.6.0
- rpy2=2.9.4
- scipy=1.4.1
- pyyaml=5.3.1
- pyfiglet=0.8
- pip:
  - corner==2.2.1
  - pypdf2==1.26.0
  - "git+https://github.com/jmeyers314/linmix.git"
